### ISSUE TITLE
Update to Hopper v4?

### ISSUE THREAD

**Issue by spotlightishere** [Sappharad/HopperPPC-Plugin#1]
Hello!

Thank you so much for making this. It has saved me so much time by allowing me to use a tool I already have for my projects.

Recently Hopper v4 came out, and its SDK is changed compared to v3. Is there any chance that this might be updated to v4?

Thanks!

**Comment by Sappharad** [comment]
Definitely, unless I run into something difficult preventing it. I was actually using Hopper v4 when I got this message. (Not PPC though)
I'll look into this in a few days.

**Comment by Sappharad** [comment]
I've committed partial support for v4. The plug-in compiles and works again, but I haven't updated it to populate operands correctly yet. I probably won't have time to look at this for about 2 weeks, so if anyone else needs it sooner feel free to submit a PR. Or keep v3 around until the remaining changes are made. (The DOL loader plug-in should be completely updated though.)

**Comment by Sappharad** [comment]
Plug-in is deprecated now that Hopper has official PPC support.
The Gamecube / Wii DOL loader has been updated to use the built in PPC decompiler and I'll continue to support that since it works well.
