### ISSUE TITLE
Missing SDK Documentation.pdf?

### ISSUE THREAD

**Issue by NicholasMoser** [Sappharad/HopperPPC-Plugin#11]
Hello,

I'm trying to find the SDK Documentation.pdf mentioned in the README.md.

Is this located in the repository or somewhere else? Sorry if I'm missing the obvious :)

Thanks!

**Comment by Sappharad** [comment]
The SDK Documentation comes with the Hopper SDK. Per the instructions, when you download this repository it needs to be placed inside of the SDK folder because the paths to the SDK are relative.

**Comment by Sappharad** [comment]
The SDK is at the bottom of the downloads page at the hopper site
https://www.hopperapp.com/download.html

**Comment by NicholasMoser** [comment]
Thanks! Appreciate it
