### ISSUE TITLE
#import <Hopper/Hopper.h> file not found

### ISSUE THREAD

**Issue by mikemilla** [Sappharad/HopperPPC-Plugin#3]
Hey there,

Sorry for my noobieness with this, but I can't seem to get xCode project to build.

I looked through the build settings to see where the plugin is actually being installed. Traced the installation directory to the directory on my computer (`$(USER_LIBRARY_DIR)/Application Support/Hopper/PlugIns/v4/CPUs`), but I am not seeing anything created in that direction. The PlugIns/v4 directory is missing all together.

I am using a demo version of Hopper. (Not sure if that has anything to do with it)

Thanks

**Comment by Sappharad** [comment]
You need to download the hopper SDK. 
This project needs to be placed inside that directory to find those files. It's a relative path, look under header search paths if your still have trouble. Also the current build hasn't been completely updated for the latest hopper yet.

**Comment by mikemilla** [comment]
Ok @Sappharad thank you.
I've been searching for the Hopper SDK download link, but can't seem to find it. Could you provide a link? Sorry :/

**Comment by Sappharad** [comment]
https://www.hopperapp.com/download.html?

**Comment by Sappharad** [comment]
Closing issue, assuming that it was resolved. Hopper supports PPC now anyway, and the DOL plug-in is updated and "works for me" with that.

**Comment by mikemilla** [comment]
@Sappharad Thanks, I did get this resolved.
